### ISSUE TITLE
Where is the "get_multi_class_labels" in brats_2019/unet3d/generator.py?

### ISSUE THREAD

**Issue by 675492062** [woodywff/brats_2019#8]
Where is the function "get_multi_class_labels" in brats_2019/unet3d/generator.py?

**Comment by woodywff** [comment]
Sorry, since I set the `overlap_label` `True` all the time, I deleted this deprecated function inherited from  [this work](https://github.com/ellisdg/3DUnetCNN). If you wanna try it, you could find it in that repository.

**Comment by 675492062** [comment]
OK, thanks for your reply
